name: GitHub Pages

on: 
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        
    - name: Install
      run: npm ci

    - name: Build locales
      run: npm run locales
    
    - name: Build
      run: npm run build

    - name: Setup files
      run: mkdir pages &&
           cp index.html pages/ &&
           cp index.css pages/ &&
           cp -r build/ pages/ &&
           rm pages/build/.noignore
    
    - name: Check folders
      run: ls
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
        exclude_assets: ''
